### ISSUE TITLE
Android raw ext4 system.img

### ISSUE THREAD

**Issue by superr** [cubinator/ext4#1]
Hello,

First, thank you for creating this module :) I am interested in getting it to work with the raw Android ext4 system.img. As you can see, your example.img works perfectly:

```
G:\Documents\ext4>python3
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ext4
>>> file = open("example.img", "rb")
>>> volume = ext4.Volume(file, offset = 0)
>>> root = volume.get_inode(ext4.Volume.ROOT_INODE)
>>> example_dir = volume.root.get_inode("example_dir")
>>> ext4.Tools.list_dir(volume, example_dir)
drwxr-xr-x    1.00 KiB  .
drwxr-xr-x    1.00 KiB  ..
-rw-r--r--    12 bytes  example_file
-rw-r--r--   66.69 KiB  example_image.jpg
>>> file.close()
```

Here is what happens when I open a raw Android ext4 system.img:

```
>>> file = open('system.img', 'rb')
>>> volume = ext4.Volume(file, offset = 0)
>>> root = volume.get_inode(ext4.Volume.ROOT_INODE)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "G:\Documents\ext4\ext4.py", line 428, in get_inode
    return Inode(self, inode_offset, inode_idx = inode_idx)
  File "G:\Documents\ext4\ext4.py", line 496, in __init__
    self.inode = volume.read_struct(ext4_inode, offset)
  File "G:\Documents\ext4\ext4.py", line 451, in read_struct
    return structure.from_buffer_copy(self.read(offset, ctypes.sizeof(structure)))
ValueError: Buffer size too small (0 instead of at least 160 bytes)
```

At first I thought it might be a ram issue as the system.img was 3.7GB, but then I tried a 1GB system.img and got the same error. 

If you need more information or a link to a raw Android ext4 system.img, please let me know and I will be happy to provide it. Thanks for your work on this :)

**Comment by cubinator** [comment]
There comes only one possibility to my mind that might be causing this problem: Maybe the offset is off causing my module to read wrong values for the block_size or the position of the inode tables, etc. From what I'm reading on the internet the system.img file seems to be packed, so that might be another cause for the problem.

Unless the system.img contains sensible data, you can give me a link to the image. Otherwise you can give me the first few mega bytes (maybe less than 32 MB), so that I can check, what my script is actually reading and whether it is actually reading an ext4 image.

**Comment by superr** [comment]
Thank you for responding so quickly :)

Here is a link to the 1GB system.img. It is raw ext4, and mounts as a loop device in Linux with no issues. I hope it helps :)

https://www.androidfilehost.com/?fid=746010030569950766

**Comment by cubinator** [comment]
Ah, that is an interesting bug: ext4 separates its data into "groups" each of which is described by a group descriptor structure (obviously). The size of this strucutre depends on some factors at creation time, but is specified in the volume's superblock. In your case it is 32 bytes (instead of the typical 64 bytes).
In line 407 I use this size to step over the group descriptor table and read each entry. But even though every step is 32 bytes long, the script actually reads 64 bytes at every step, because in line 451 I used the python-structure's byte size instead of the specified byte size.

I try to fix it tomorrow, but I can't promise (because I'm pretty busy lately).

**Comment by superr** [comment]
Thank you for looking at this. I really appreciate it. No hurry at all :)

Additionally, I have 2 feature requests if they are not already available. No hurry or pressure :)

1. Read file xattr including security.selinux and security.capabilities
2. Ability to write all files in the ext4 img to a chosen local directory keeping the directory structure intact

Thanks again for the help :)

**Comment by cubinator** [comment]
Ok, the read error is fixed. But there are some problems with your feature requests:

1. I could implement reading extended attributes in general (e.g. reading the raw xattr name-value-pairs), but in your image the xattrs are somewhat ill-formatted, specifically the inline-xattrs: Normally inodes are stored on disk with a lot of padding enabling inline-data (so that little files don't need their own disk blocks). In your system image the `ext4_inode.i_projid` and `ext4_xattr_ibody_header.h_magic` fields seem to overlap and I couldn't find any documentation telling me why this is the case or why my system was still able to read those attributes. I couldn't find any way to distinguish between volumes where there is this overlap and volumes where there is no overlap.

2. Writing files is somewhat complicated. It's not just like `fopen`, `fwrite` and `fclose`. To write a new file, I would need to find unused disk blocks, generate extent trees, link them up with unused inodes and add them to the directory (possibly having to reallocate the directory file). Then there are those usage-bitmaps for inodes and disk blocks and I never got checksums to work (sparse documentation), so modifying inodes without making the system complain about wrong checksums is impossible for me. For simple cases like writing to files without increasing their size you could utilize the `BlockReader` instance returned by `inode.open_read()`, which has useful methods like `get_block_mapping()`, `get_range_mapping()` (which take their data from the field `block_map`).

**Comment by superr** [comment]
Thank you for fixing the read error :)

Here is the source for the [make_ext4fs](https://github.com/superr/make_ext4fs) binary that was used to create the system.img I sent. Not sure if it helps, but it is the standard way of creating the raw Android ext4 system.img.

If I open the system.img in a hex editor, I can see the security.selinux xattr over in the strings column but I don't know which files they go with. Some of the contexts you can tell which file they belong to from the context string, but most just use system_file.

I have source for a binary written in C that grabs the uid, gid, mode, security.selinux (file contexts), and security.capabilities (file capabilities) for all files in the system.img. It also extracts all the files. The problem is that I can't compile it properly for Windows (due to lack of experience) and the Python project I need this for must be cross-platform. 

I completely understand if this is more than you want to take on. Just trying to find a solution and this module seems the closest I have found along with your knowledge of ext4 :)

**Comment by cubinator** [comment]
Well, between [those two lines](https://github.com/superr/make_ext4fs/blob/81ca392f444dd731127dca0b34b17443c486a825/extras/ext4_utils/ext4.h#L289-L290) is a `__le32 i_projid;` missing, which you can find in the [newer version of this header file](https://github.com/torvalds/linux/blob/abc36be236358162202e86ad88616ff95a755101/fs/ext4/ext4.h#L739). I can't find a way to distinguish between systems using `i_projid` and those that don't though.

**Comment by superr** [comment]
To be honest, I don't know what that means but I did check the[ latest Android source](https://android.googlesource.com/platform/system/extras/+/android-8.1.0_r9/ext4_utils/include/ext4_utils/ext4.h#289) and it is still missing.

Would it be a difficult adjustment to make for example a different version of your module to work with ext4 img files without `__le32 i_projid;`? I ask because my project will only be working with Android system.img. 

Thanks again for your time :)

**Comment by cubinator** [comment]
No actually not, I try to implement xattrs some time soon. Making the module work in your case should* be as simple as removing the line `("i_projid", ctypes.c_uint)` at the end of the class `ext4_inode`.

By the way: xattrs are the only feature affected by this `i_projid` problem as far as I can tell and I haven't ever seen the `i_projid` field in use.

\* I don't actually know whether this produces some unknown side effects, so I need to test it first.

**Comment by superr** [comment]
It would be amazing if you get it working!! Thank you so much for looking into this. If there is anything you need from me please let me know :)

**Comment by superr** [comment]
Are you aware of any Python3.6 specific code in your module besides fstrings? I ask because my project is currently written for Python3.5. Python3.5 is the newest Python3 available in the Ubuntu 16.04 LTS repos. If fstrings are the only 3.6+ specific code, I think I can manage replacing with format() to work with 3.5. Does this seem reasonable?

**Comment by cubinator** [comment]
As far as I know fstrings are the only 3.6+ feature. My code literally just consists of ctypes structures and byte conversions and for loops, so replacing the fstrings should be enough to make it work in 3.5.

**Comment by superr** [comment]
Perfect! Thanks again for your time :)

**Comment by superr** [comment]
I read your post again about writing files and realized you may have thought I want to write new files into the ext4 img. That is not the case. Sorry if I was confusing. 

The full extent of what I need is as follows:

1. I would like to extract all files and directories from the ext4 img into a specified directory on a local hdd ("/home/superr/system" for example) and keep the directory structure intact. The files do not need to keep their uid, gid, mode, or xattr after extraction. I only need the files extracted.

2. I would like to generate a list of all files and directories with file name, uid, gid, mode, and file capabilities all on one line like this:
     `system/bin/run-as 0 2000 0750 capabilities=192`
if there are no capabilities for a file (which will be the case for most files):
     `system/bin/run-as 0 2000 0750`

3. I would like to generate a list of file name and selinux context on the same line like this:
     `system/bin/run-as u:object_r:runas_exec:s0`

That sums up what I am trying to do. Again, if you are not up for all of this please don't hesitate to say so. I really appreciate the time you have spent writing this and helping me :)

BTW, the system.img reads perfectly now :) Replacing the fstrings also works perfectly in Python3.5 :)

**Comment by cubinator** [comment]
Well, without writing into the image, the task becomes much much simpler: My script can already read directories, files (e.g. their content) and show their uid, gid, mode (even in formatted form like -rwxr-xr-x including setuid, setgid and sticky), so only xattrs remain, which I will implement soon: They have a similar structure to directories, so it shouldn't take much time to implement them. When this is done, you should only need to replace the fstrings and remove the `i_projid` line and you are practically done.

**Comment by superr** [comment]
Wonderful :) Thank you so much!!

**Comment by superr** [comment]
File extraction is working great, but currently only the top level is being extracted. I need to find a good way to iterate recursively through all files and directories without first knowing their names or paths. Any suggestions?

**Comment by cubinator** [comment]
Yep: If `volume` is your `ext4.Volume` instance, use `volume.root`, which is the volume's root inode (the root directory). It is a normal directory where you can `open_dir()` to iterate over its entries.

**Comment by superr** [comment]
Thank you for the response :) I did figure that out, but I only end up with the top level root directory entries. "app" for instance shows up, but not "app/BasicDreams/oat/arm64/BasicDreams.odex". I am probably just missing something.

**Comment by cubinator** [comment]
`open_dir` gives you tuples `(name, entry_inode, type)`. If `type == ext4.Inode.IT_DIRECTORY` then you know that this entry is a directory, so you can call `volume.get_inode(entry_inode).open_dir()` to get the entry's sub entries. In case you want to get the root directory with `volume.get_inode` for a cleaner recursive implementation, you can do `volume.get_inode(ext4.Volume.ROOT_INODE)`.

**Comment by superr** [comment]
It seems I have a lot of learning to do, and you make it sound so easy :) Now that I know it can be done and the general layout I will try to figure it out. Thanks again for the help :)

**Comment by cubinator** [comment]
Well the recursive definition looks like this
```
def scan_dir (root_inode):
    for entry_name, entry_inode_idx, entry_type in root_inode.open_dir():
        if entry_type == ext4.Inode.IT_DIRECTORY:
            # Things to do for directories only
            if entry_name != "." and entry_name != "..":
                scan_dir(root_inode.volume.get_inode(entry_inode_idx)) # Recursion
        else:
            # Things to do for files only

        # Things to do for both types

scan_dir(ext4.Volume(image_file).root) # Start recursion at the root directory "/"
```
EDIT: There was a mistake in the for loop, that should be fixed now.
EDIT 2: Or a less low-level solution
```
def scan_dir (root_inode):
    for entry_name, entry_inode_idx, entry_type in root_inode.open_dir():
        entry_inode = root_inode.volume.get_inode(entry_inode_idx)

        if entry_inode.is_dir:
            # Things to do for directories only
            if entry_name != "." and entry_name != "..":
                scan_dir(entry_inode) # Recursion
        else:
            # Things to do for files only

        # Things to do for both types

scan_dir(ext4.Volume(image_file).root) # Start recursion at the root directory "/"
```
EDIT 3: No parentheses behind `is_dir` (forgot that it's a property and not a method).
EDIT 4: Ignore "." and "..", they are actual directory entries on disk.

**Comment by superr** [comment]
Wonderful :) I can customize this from here. I really appreciate your help :)

**Comment by superr** [comment]
I was wrong. Sorry, one last question. How do I determine the full path of a file when using these recursion methods. For example, if I want to print the full path to all the files relative to the ext4 root dir like this:
`app/BasicDreams/oat/arm64/BasicDreams.odex`
Right now i only get:
`BasicDreams.odex` for files and `arm64` for directories for example.

I truly am sorry for all the questions. Thanks again :)

**Comment by cubinator** [comment]
The path is a little bit tricky, because inodes don't have names. Instead directory inodes contain a list of file names mapping to inodes. Hence you need to remember the file path while iterating, e.g. by introducing a second (optional) argument to `scan_dir` like this:
```
volume = ext4.Volume(image_file)

def scan_dir (root_inode, root_path = ""):
    for entry_name, entry_inode_idx, entry_type in root_inode.open_dir():
        if entry_name == "." or entry_name == "..":
            continue # Ignore "." and ".." directories

        entry_inode = root_inode.volume.get_inode(entry_inode_idx)
        entry_inode_path = root_path + "/" + entry_name # Remember path

        if entry_inode.is_dir:
            # Things to do for directories only
            print("DIR: {0:s}".format(entry_inode_path))
            scan_dir(entry_inode, entry_inode_path)
        else:
            # Things to do for files only
            print("FILE: {0:s}".format(entry_inode_path))

        # Things to do for both

scan_dir(volume.root)
# image_file.close()
```

**Comment by superr** [comment]
That is beautiful, thank you so much :)

**Comment by superr** [comment]
So sorry again, but how do I get the uid and gid for a file/directory? I can get mode like this:
```mode = entry_inode.mode_str```
but there does not appear to be a `uid_str` or `gid_str` option. Thanks

**Comment by cubinator** [comment]
The UID and GID of an inode are stored in the `ext4_inode` structure, which you can access from the `inode` field of an `ext4.Inode` instance. E.g.
```
inode = volume.get_inode(some_inode_idx) # or volume.root.get_inode("some", "path", "to", "inode")
uid = inode.inode.i_uid # inode is an ext4.Inode instance (abstraction)
gid = inode.inode.i_gid # inode.inode is an ext4_inode structure (raw data, ctypes.Structure)
```

**Comment by superr** [comment]
Perfect! Thanks again :)

**Comment by cubinator** [comment]
I'm currently implementing xattrs and I stumbled upon a way to distinguish between your ext4 version and the newer one, so you won't need to alter the script, when it's ready (except for the fstrings): The problem was the size of the `ext4_inode` structure (156 bytes in your version, 160 bytes in every other version). Technically every such structure is just 128 bytes in size, which is a fixed value for every version. Everything passing the 128 bytes is declared "addition data" and its size must be specified in the inode's `i_extra_isize` field, which gives me a way to calculate the offset to the xattr structures :)

**Comment by superr** [comment]
Nice catch. Looking forward to it :)

**Comment by cubinator** [comment]
Ok, extended attributes are now implemented. You can access them via `inode.xattrs()`, which gives you an iterable of tuples `(name, value)` where `name` is a string and `value` is a bytes object with the raw attribute value. security.selinux is plain text, so you can do `value.decode("utf8").strip()`, but security.capability is some kind of binary format, which I have not been able to find any documentation on.

Btw. I uploaded a Python 3.5 version of my code (ext4.py35.py) where I replaced the fstrings with `.format()` calls.

**Comment by superr** [comment]
Simply amazing. Thank you so much :) 

Regarding the capabilities, this gives me exactly what I need. I just need to figure out how to get it. In this example:
```
'security.capability', b'\x01\x00\x00\x02\x00\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```

`b'\x01\x00\x00\x02'` seems to be some kind of capability prefix. The part we are interested in is `b'\x00\x00\x80'` in decimal format - 128. This value seems to vary in length however.

In this example:
```
'security.capability', b'\x01\x00\x00\x02\xc0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```
We want `b'\xc0'` which becomes 192 in decimal

This example is complicated:
```
'security.capability', b'\x01\x00\x00\x02@\x00\x00@\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00'
```
The value we want should be 1073741888 in decimal but I have no idea how to get that from here.

Thanks again for your help :)

**Comment by cubinator** [comment]
Do you have some source explaining this format or implementing this format? My first guess would probably be
```
def capability (data): return int.from_bytes(data[4:), "little")
```

**Comment by superr** [comment]
Thank you for the attempt, but unfortunately it does not work. 

The only documentation I have is the make_ext4fs source I sent before. There is a [android_filesystem_capability.h](https://github.com/superr/make_ext4fs/blob/master/core/include/private/android_filesystem_capability.h) file that probably helps you but looks very confusing to me. Thanks again for everything :)

**Comment by superr** [comment]
Ok, found the solution for capabilities :)

This provides the decimal I require. 

```list(struct.unpack("<IIIII", value))[1]```

Everything works perfectly now. I can't thank you enough :)

**Comment by cubinator** [comment]
So the value you were searching was [`vfs_cap_data.data[0].permitted`](https://github.com/superr/make_ext4fs/blob/master/core/include/private/android_filesystem_capability.h#L62-L68), which you can also get with
```
def capability (data): return int.from_bytes(data[4:8], "little")
```
I was close :)

**Comment by superr** [comment]
You were close indeed :) I really appreciate all you have done. Thank you again :)

**Comment by superr** [comment]
Hello again,

I am getting some errors when doing `entry_inode.open_read()` on 2 different raw ext4 Android img files for the same device. [Here is the smaller of the 2 img files](https://www.androidfilehost.com/?fid=890129502657581038). Hopefully the problem is the same for both.

```
line 862, in open_read
    return BlockReader(self.volume, len(self), mapping)
  File "ext4.py", line 959, in __init__
    raise BlockMapError("byte_size doesn't match up with count of mapped blocks")
ext4.BlockMapError: byte_size doesn't match up with count of mapped blocks
```
Most of the inodes read without issue, but the following files in the linked img fail:
```
/bin/cnss_diag
/bin/thermal-engine
/lib/libmmcamera2_sensor_modules.so
/lib/libchromatix_imx179_video_qtr_16_9_3a.so
/lib/libchromatix_imx179_video_16_9_3a.so
/lib/rfsa/adsp/chre_drv_wifi.so
/lib/rfsa/adsp/chre_drv_loc.so
/lib/rfsa/adsp/libnanohub_slpi_skel.so
/lib/libchromatix_imx378_video_hfr_60_3a.so
/lib/libmmcamera_sony_imx179_eeprom.so
/lib/libchromatix_imx378_video_hfr_120_3a.so
/lib/libchromatix_imx378_zsl_snapshot_3a.so
/lib/dsp/EtsiEaacPlusEncAndCmnModule.so.1
/lib/dsp/mmecns_module.so.1
/lib/libchromatix_imx378_video_hfr_240_3a.so
/lib/libmmcamera_sony_imx378_eeprom.so
/lib/libmmcamera_imx179_htc.so
/lib/libchromatix_imx179_zsl_snapshot_3a.so
/lib/libmmcamera_imx378_htc.so
/lib/libchromatix_imx378_video_16_9_3a.so
/lib64/libfastcvopt.so
/firmware/adsp.b05
/firmware/adsp.b02
/firmware/adsp.b03
/firmware/slpi.b03
/firmware/adsp.b08
/firmware/synaptics_bl71.img
/firmware/hotsound.sound_model
/firmware/fpctzappfingerprint.b03
/firmware/slpi.b05
/firmware/slpi.b08
/firmware/widevine.b03
/firmware/nanohub.full.bin
/firmware/cpe_9335.b08
/firmware/slpi.b13
```

Thank you again for all your time. I hope this is not a difficult fix :)
