### ISSUE TITLE
How to check If files in each directory all share same permissions.

### ISSUE THREAD

**Issue by pr0f35510n4l** [cubinator/ext4#12]
Hello, first of all thank you for your help with symlinks.
I need to do 1 more thing.

How would I find all subdirectories in the ext4 image and inside each directory check if the files inside share same mode (permissions) with other files, and if they do, do something.

I've already written code how to check the permissions for every file in system.img (the ext4 image), assume it's value as: `f"{permissions}"`

Here's my code to check permissions: https://github.com/4u7157/ext4/blob/patch-1/ext4.py35.py
( I added it at End Of File )

I guess I have to use tuple but I am fairly new to python and I don't know.

**Comment by cubinator** [comment]
The `mode_str` attribute computes the string representation of the permissions everytime you access it, so consider storing it in some variable and using the variable in place of `mode_str`.

And instead of your `perm` function you can get the permissions as zero-padded octal string as follows.

    #   ext4.Inode object
    #    |
    #    |    underlying ext4.ext4_inode structure
    #    |     |
    #    |     |     integer containing the permissions(*)
    #    |     |      |
    #    |     |      |     extract the rwxrwxrwx part
    #    |     |      |     (use 0xFFF, if you also need the
    #    |     |      |     "sticky bit", "set gid", "set uid")
    #    |     |      |       |
    #    v     v      v     vvvvv

    f"{inode.inode.i_mode & 0x1FF:0>4o}"

    #                             ^^^^
    #         Format instruction: '0' zero-padded, '>' justified
    #             right, '4' characters, 'o' octal string


    # (*)               u uugggooo
    #                   r wxrwxrwx permissions
    # i_mode = 0b00000000 00000000
    #            ffffUGs
    #              | |||
    #              | ||s: "Sticky bit"
    #              | |G: "Set GID"
    #              | U: "Set UID"
    #              f: inode type (file/directory/symlink/...)
    #
    # Those bits are defined in the S_I* constants in class ext4_inode

Let me know, if you need help with something else.

**Comment by pr0f35510n4l** [comment]
How would I list directories only?

**Comment by pr0f35510n4l** [comment]
I mean if image was extracted i'd do: 
```
import glob

dirs = glob.glob(my_path + '/**/', recursive=True)
``` 
to list directories only. Is it possible to do inside the ext4 image without extracting it

EDIT 2: Switched to python code

**Comment by cubinator** [comment]
Yes, you can call `open_dir` on every `ext4.Inode` instance representing a directory (e.g. `volume.root`). It returns an iterator that gives you a tuple `(file_name, inode_idx, file_type)` for every entry in the directory. The sub-directories are those entries where `file_type == ext4.InodeType.DIRECTORY`. You can write a little wrapper function that goes through the entire tree recursively:

    import ext4

    import ext4

    def scan_subdirectories (scan_root):
        """
        Scans the directory tree of scan_root (ext4.Inode) top-bottom and returns an iterator that generates an ext.Inode
        instance for every sub-directory found (including scan_root itself).
        """
        volume = scan_root.volume

        def intern (inode):
            yield inode

            for file_name, inode_idx, file_type in inode.open_dir():
                if file_name in (".", ".."): continue
                elif file_type == ext4.InodeType.DIRECTORY:
                    yield from intern(volume.get_inode(inode_idx))

        yield from intern(scan_root)

**Comment by pr0f35510n4l** [comment]
thank you for helping sir
