### ISSUE TITLE
Some symlinks cannot be decoded with utf8

### ISSUE THREAD

**Issue by superr** [cubinator/ext4#3]
Hello,

Most things are working great now, thanks again :)

There is a small problem with some symlinks. Normally when we do:
```
symbolic_link = root.get_inode("example_symlink")
print(symbolic_link.open_read().read())
```
We get output that can easily be decoded with `.decode('utf8')`:
```
b'/system/lib64/libHwIAware_jni.so'
```
However, on some symlinks I get output like this instead:
```
b'\xfe\xff\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```
On the mounted img, these commands produce the correct target link:
```
$ sudo readlink output/etc/facerecognition/face_detect_classifiers/CAMERA_HAAR_1.dat
/vendor/etc/facerecognition/face_detect_classifiers/CAMERA_HAAR_1.dat

>>> os.path.realpath('output/etc/facerecognition/face_detect_classifiers/CAMERA_HAAR_1.dat')
'/vendor/etc/facerecognition/face_detect_classifiers/CAMERA_HAAR_1.dat'
```
Any ideas?

Thanks for your time :)

**Comment by cubinator** [comment]
What does `volume.read(327678 * volume.block_size, your_strange_sym_link.inode.i_size)` return, if `your_strange_sym_link` is the `ext4.Inode` instance of your strange symbolic link?

**Comment by superr** [comment]
It provides exactly the correct answer :)

```
b'/vendor/etc/facerecognition/face_detect_classifiers/CAMERA_HAAR_1.dat'
```

**Comment by superr** [comment]
Thanks again for this :)

**Comment by superr** [comment]
Hello again,

The new extraction is woring perfectly now, thanks again :)

Unfortunately there are still some symlinks that are not working properly, even with the new method for strange symlinks. I guess these are even more strange:
```
etc/facerecognition/face_detect_classifiers/CAMERA_HAAR_1.dat
etc/facerecognition/face_detect_classifiers/CAMERA_HAAR_11.dat
etc/facerecognition/face_detect_classifiers/CAMERA_HAAR_12.dat
etc/facerecognition/face_detect_classifiers/CAMERA_HAAR_Weight.dat
etc/facerecognition/face_detect_classifiers/CAMERA_LAB_1.dat
etc/facerecognition/face_detect_classifiers/CAMERA_LAB_11.dat
etc/facerecognition/face_detect_classifiers/CAMERA_LAB_12.dat
etc/qdcm_calib_data_AUO_NT51021B_8P0_VIDEO_TFT_1200_x_1920.xml
etc/qdcm_calib_data_AUO_NT51021_8P0_VIDEO_TFT_1200_x_1920.xml
etc/qdcm_calib_data_BOEG6_TD4100_5P5_VIDEO_TFT_720_x_1280.xml
etc/qdcm_calib_data_BOE_ILI9881C_5P0_VIDEO_IPS_720_x_1280.xml
etc/qdcm_calib_data_BOE_JD9366_8P0_VIDEO_TFT_800_x_1280.xml
etc/qdcm_calib_data_BOE_NT51017TE_9P6_VIDEO_TFT_800_x_1280.xml
etc/qdcm_calib_data_BOE_NT51017_9P6_VIDEO_TFT_800_x_1280.xml
etc/qdcm_calib_data_BOE_NT51021_10P1_VIDEO_TFT_1200_x_1920.xml
etc/qdcm_calib_data_BOE_OTM1289_5P0_VIDEO_TFT_720_x_1280.xml
etc/qdcm_calib_data_BOE_TD4100_5P5_VIDEO_TFT_720_x_1280.xml
etc/qdcm_calib_data_CPT_HX8394F_5P0_VIDEO_IPS_720_x_1280.xml
etc/qdcm_calib_data_DJN_ILI9881CS_5P0_VIDEO_TFT_720_x_1280.xml
etc/qdcm_calib_data_INX_FT8607_5P5_VIDEO_TFT_720_x_1280.xml
etc/qdcm_calib_data_INX_JD9367_8P0_VIDEO_TFT_800_x_1280.xml
etc/qdcm_calib_data_INX_NT36525_5P5_VIDEO_TFT_720_x_1280.xml
etc/qdcm_calib_data_INX_NT51021_10P1_VIDEO_TFT_1200_x_1920.xml
etc/qdcm_calib_data_INX_NT51021_8P0_VIDEO_TFT_1200_x_1920.xml
etc/qdcm_calib_data_OFILM_NT35521SB_5P0_VIDEO_TFT_720_x_1280.xml
etc/qdcm_calib_data_OFILM_NT35521S_5P0_VIDEO_TFT_720_x_1280.xml
etc/qdcm_calib_data_TCL_HX8394F_5P0_VIDEO_IPS_720_x_1280.xml
etc/qdcm_calib_data_TM_TD4100_5P5_VIDEO_TFT_720_x_1280.xml
etc/qdcm_calib_data_TXD_ILI9881CS5_5P0_VIDEO_TFT_720_x_1280.xml
etc/qdcm_calib_data_TXD_ILI9881CS_5P0_VIDEO_TFT_720_x_1280.xml
etc/qdcm_calib_data_TXD_ILI9881C_5P0_VIDEO_IPS_720_x_1280.xml
```
Here is a link to the [system.img](http://sr-code.com/cubinator/filemanager.php?file=system.img_test2.zip) containing these extra strange symlinks. `readlink extra.strange.symlink` does produce the correct result on the mounted img.

So far I am doing something like this:
```
symbolic_link = root.get_inode('example_symlink')
try:    
    link_target = symbolic_link.open_read().read().decode('utf8')
except:
    link_target = volume.read(327678 * volume.block_size, symbolic_link.inode.i_size).replace(b'\x00', b'').decode('utf8')
```
This worked for the previous strange symlinks, but not these.

Thanks again for all your help :)

EDIT: Added a few more extra strange symlinks to the list

**Comment by cubinator** [comment]
Replace the line after `except:` with

    link_target_block = int.from_bytes(inode.open_read().read(), "little")
    link_target = volume.read(link_target_block * volume.block_size, symbolic_link.inode.i_size).decode("utf8")

The `327678` was just an intuition after seeing `b'\xfe\xff\x04\x00...\x00'` in your output and stands for the block index in which the link target is stored. The `symbolic_link.inode.i_size` then specifies the length of the link target string, so no `.replace(b"\0", b"")` is required (or at least shouldn't be required).

**Comment by superr** [comment]
Genius!! It works perfectly. Thank you so much again for all your time and help :)
