### ISSUE TITLE
xattrs security.capability is not always accurate

### ISSUE THREAD

**Issue by superr** [cubinator/ext4#4]
Hello again,

I think there may be another place security.capability are located. Or more likely, I am doing something incorrectly again. The capabilities are always detected for the right files, but sometimes we get a `0` instead of the correct capability. Both the mounted img using the `getcap` utility and `sysXtract` are able to pull them correctly so I am sure they are there somewhere.

I am currently using the following to access the capabilities:
```
for i in list(entry_inode.xattrs()):
	if i[0] == 'security.capability':
		cap = str(int.from_bytes(i[1][4:8], "little"))
```
This works for most of them, but not these for example:
```
bin/glgps47531      capability=0
bin/glgps47531cl      capability=0
bin/glgps4774      capability=0
bin/glgps4774cl      capability=0
bin/gnss_control_hisi      capability=0
bin/gnss_engine_hisi      capability=0
```
They should be:
```
bin/glgps47531     capability=68719476736
bin/glgps47531cl      capability=68719476736
bin/glgps4774      capability=68719476736
bin/glgps4774cl      capability=68719476736
bin/gnss_control_hisi      capability=68719476736
bin/gnss_engine_hisi      capability=68719476736
```
Here is the [vendor.img](http://sr-code.com/cubinator/filemanager.php?file=vendor.img_test.zip) where the above capabilities exist.

Sorry for asking so many questions. You have been an enormous help and I can't thank you enough :) 

EDIT: Here is an example from the same vendor.img where the capability works correctly in case it helps:
```
bin/run-as      capability=192
```

**Comment by cubinator** [comment]
My `getcap` just puts out a name instead of a number, so please follow these instructions for me to see which bytes `getcap` or `sysXtract` actually reads.

1. Create a copy of the vendor.img you linked in this issue, let's call it `vendor2.img` and don't mount the image.
2. In `vendor2.img` change the 20 bytes beginning at offset `0x374FFEC` to `01 00 00 02 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F` or optionally run the following python code

        file = open("vendor2.img", "rb+")
        file.seek(0x374FFEC) // Offset of the security.capability xattr of bin/gnss_control_hisi
        file.write(bytes(range(16)))
        file.close()

3. Obtain and post the capability value of `vendor2.img/bin/gnss_control_hisi` (now you can mount the image for this step, if you need to)

This should allow me to identify the bytes your programs are reading.

**Comment by superr** [comment]
Thank you for looking into this :)

My getcap also outputs a name/names. The name/names are assigned numbers [from here](https://github.com/superr/make_ext4fs/blob/c05dd49373d31dac0e9f95540995750da96cef50/core/include/private/android_filesystem_capability.h#L72). Take each of the numbers from the names (there may be more than one), do `number^2`, then add them all together to get the final capability number I am after. 

However, as I mentioned `sysXtract` is able to read this number from somewhere so it must be there, right? I am so sorry for causing so much trouble. Do you still want me to do what you mentioned now that you know getcap does not output the number itself?

Thanks again :)

**Comment by cubinator** [comment]
Don't you mean `2 ^ number` (2 * 2 * ... * 2 `number` times) instead (or even faster `1 << number`)?

**Comment by superr** [comment]
In python I mean `2 ** number`

Sorry for the confusion :)

EDIT:
Here is a dict with the cap name values if it helps:
```
capdef = {
	'cap_chown':0,
	'cap_dac_override':1,
	'cap_dac_read_search':2,
	'cap_fowner':3,
	'cap_fsetid':4,
	'cap_kill':5,
	'cap_setgid':6,
	'cap_setuid':7,
	'cap_setpcap':8,
	'cap_linux_immutable':9,
	'cap_net_bind_service':10,
	'cap_net_broadcast':11,
	'cap_net_admin':12,
	'cap_net_raw':13,
	'cap_ipc_lock':14,
	'cap_ipc_owner':15,
	'cap_sys_module':16,
	'cap_sys_rawio':17,
	'cap_sys_chroot':18,
	'cap_sys_ptrace':19,
	'cap_sys_pacct':20,
	'cap_sys_admin':21,
	'cap_sys_boot':22,
	'cap_sys_nice':23,
	'cap_sys_resource':24,
	'cap_sys_time':25,
	'cap_sys_tty_config':26,
	'cap_mknod':27,
	'cap_lease':28,
	'cap_audit_write':29,
	'cap_audit_control':30,
	'cap_setfcap':31,
	'cap_mac_override':32,
	'cap_mac_admin':33,
	'cap_syslog':34,
	'cap_wake_alarm':35,
	'cap_block_suspend':36,
	'cap_audit_read':37
}
```

**Comment by cubinator** [comment]
After reading some `cap_to_text()` source and experimenting with `capsh --decode=CAP_MASK` I crafted  this function

    def capability_mask (inode):
        try:
            vfs_cap_data = next(value for name, value in inode.xattrs() if name.lower() == "security.capability")
            cap_permitted = vfs_cap_data[4:8] + vfs_cap_data[12:16]
            return int.from_bytes(cap_permitted, "little")
        except StopIteration:
            return 0

which is not yet field tested on a large scale, but should (in theory) give you the right capabilities (I haven't yet understood capability inheritance, hence the "in theory" part).

P.S. In [this post](https://github.com/cubinator/ext4/issues/1#issuecomment-362877922) you said that from the raw security.capability data `b'\x01\x00\x00\x02@\x00\x00@\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00'` we should get the capability mask `1073741888`. So I inserted this raw capability data via a hex editor into the `bin/gnss_control_hisi` file (from the last image you linked here), mounted it, ran `getcap vendor_img/bin/gnss_control_hisi` and got

    system/bin/gnss_control_hisi = cap_setgid,cap_audit_control,cap_syslog+ep

which according to the "2 * 2 * ... * 2"-method gives me

    CAP_SETGID = 6         // 2 ** 6  = 0x0000_0000_0040
    CAP_AUDIT_CONTROL = 30 // 2 ** 30 = 0x0000_4000_0000
    CAP_SYSLOG = 34        // 2 ** 34 = 0x0004_0000_0000
    ----------------------------------------------------
                          18253611072 = 0x0004_4000_0040 < Result of my capability_mask_method()
                          ---------- but not -----------
                           1073741888 = 0x0000_4000_0040 < Your result
                      Only one bit different ^

The fact that only one bit is off makes me think that you might have missed the bit when calculating the mask.

**Comment by superr** [comment]
Absolutely amazing!! It's perfect on several img files from different vendors. Thank you so much for everything :)

It turns out, the only thing I needed to change was `vfs_cap_data[4:8] + vfs_cap_data[12:16]`. I was using `vfs_cap_data[4:8]` before. 

By the way, that 1 bit off is the reason I am working on this project actually. I have mentioned that I previously used `sysXtract` for this, but some of the capabilities were off in some OS's. That was one of them I guess. Sorry it ended up in my example and possibly threw you off a bit.

Thank you again for all your time and effort :)

**Comment by superr** [comment]
Still working perfectly. Thanks again :)
