### ISSUE TITLE
Retrieve block count and size of device from ext4 img file

### ISSUE THREAD

**Issue by superr** [cubinator/ext4#6]
Hello,

Your module is working absolutely perfectly, thank you again!

This is not an issue, more of a feature request if it is not already possible. I have run across some ext4 img files that will not mount in Linux. After attempting to mount, ```dmesg | tail``` produces something like this:

```
EXT4-fs (loop0): bad geometry: block count 780231 exceeds size of device (753664 blocks)
```

Finally the request:
Is it possible with your module to retrieve the 2 sizes listed in the dmesg above without trying to extract the ext4 img?

Thank you for your time :)

**Comment by cubinator** [comment]
You can retrieve the stored block count from the superblock and calculate the real block count like this

    import io
    
    # Open volume. In case Volume raises an Error, add ignore_flags=True to the parameters
    volume_file = open("/your/ext4/image", "rb")
    volume = Volume(volume_file)
    
    # Block count according to the superblock ((s_block_count_hi << 32) | s_block_count_lo)
    stored_block_count = volume.superblock.s_blocks_count
    
    # Real block count (in dependence of the volume's size and the stored block size)
    volume_file.seek(0, io.SEEK_END)
    volume_size = volume_file.tell()
    
    real_block_count = volume_size / volume.block_size

**Comment by superr** [comment]
Absolutely perfect! Thank you very much :)
