### ISSUE TITLE
[Feature request / New project request] Create ext4.img files

### ISSUE THREAD

**Issue by superr** [cubinator/ext4#7]
Hello,

Is it possible and would you be willing to add support for creating an ext4.img? Ideally, it would take the following arguments:

- Path to directory of files to be included in the ext4.img
- Path to config file containing file path, uid, gid, mode, and capabilities within the ext4.img
- Path to file_contexts file containing file path and file context within the ext4.img
- Mount point (ex. / or /system)
- ext4 partition size / size of the created ext4.img
- Timestamp for included files source (ex. current local PC time, existing time from files, or custom time)

Thank you for your consideration,
SuperR :)

PS. Your ext4 module is working perfectly :)

**Comment by cubinator** [comment]
When I pass my last exam for this semester, I can _try_ to implement support for creating ext4 images, but there are some problems right from the get-go, for example my current knowledge of ext4 is limited to reading directories and files (I have no clue how common ext4 implementations allocate space, because the only ext4 documentation available to me is really sparse) and I haven't really gotten around to separate things required by ext4 specification from things that are up to the implementation.

I'll report back, when I make some progress or have questions/notes to your requirements :)

**Comment by superr** [comment]
Thank you for your reply :)

Here is the [source code of make_ext4fs](https://github.com/superr/make_ext4fs) stripped out of AOSP 6.0.1 (Android Open Source Project). It does exactly the job I need, but it is not reliable in Windows so I can't use it in my project anymore. Maybe it can help answer how space is allocated and other questions that may arise.

Another project more commonly used in Linux is [e2fsprogs](https://github.com/tytso/e2fsprogs) and the mke2fs binary. AOSP recently started using this project to build ext4.img files and dropped make_ext4fs. They created a contribution to the e2fsprogs project called [e2fsdroid](https://github.com/tytso/e2fsprogs/blob/master/contrib/android/e2fsdroid.c) that may also help. Unfortunately this utility is also not available for Windows.

Thanks for looking into this. I look forward to your progress and really appreciate your help :)
SuperR

**Comment by cubinator** [comment]
You know, before I reinvent the wheel that is ext4, it might actually be easier and less error prone for you to install VirtualBox and setup an ArchLinux system with
 - `virtualbox-guest-tool(-nox)` to move files between your host and guest system,
 - `android-tools` providing e2fsdroid,
 - `getcap` and `setcap` should be available by default and
 - a little bit of bash scripting to automate all of this.

**Comment by superr** [comment]
Thank you for the suggestion, and you are not wrong :) 

However, I am not the only one using this project and setup for many users is not possible. It is true to the point that some are not capable to figure out how to install Python packages through pip. Currently, the only external dependency my project has is Java and I even get complaints occasionally about installing it.

As a result, I am trying to figure out another way to create these ext4.img files. My project is cross-platform so the Linux/Mac users are in good shape. Windows on the other hand is a disaster when t comes to ext4. Your ext4 module has saved me with the Windows extraction, and I can't thank you enough for that :)

All of that said, I completely understand if you decline this feature/project request. It seems like a lot of work and I am simply not capable of writing it myself. I do need to find a native solution to this problem though, so it would be wonderful if you were willing to do it. I offer no pressure, but have great hope.

Thank you again for all your time and help :)

**Comment by cubinator** [comment]
Okay, I tried porting your [superr/make_ext4fs](https://github.com/superr/make_ext4fs) to Windows. Take a look at [cubinator/make_ext4fs](https://github.com/cubinator/make_ext4fs). Simply run the Makefile in the project directory, it should build all the necessary files and copy the final `make_ext4.exe` into the project directory.

I successfully compiled this project using `mingw32-make` from [MinGW-W64-build](https://mingw-w64.org/doku.php/download).

Let me know whether this works for you.

**Comment by superr** [comment]
This is a great idea, thank you for doing this :)

Compilation went well. Unfortunately I get this error when trying to build an ext4.img
```
Assertion failed!

Program: G:\Documents\tools\make_ext4fs\make_ext4fs.exe
File: make_ext4fs.c, Line 591

Expression: !directory
```
Any idea how to fix this? Thanks again for your help :)

EDIT: added the last line in the error

**Comment by superr** [comment]
This is the line causing the error:
```assert(!directory);```
I removed it, compiled again, and this time it built a valid ext4 system.img. Unfortunately the only contents were lost+found.

**Comment by superr** [comment]
I  think I found the problem. make_ext4fs.c has been crippled when compiled with mingw. Right above the error line there is a comment ```// Windows needs only 'create an empty fs image' functionality```.

I tried removing all the ```#ifndef USE_MINGW``` and got errors and a failed compilation.

I was previously compiling on cygwin, and it does create valid ext4 system.img, but it errors sometimes and does not include all files or corrupts them. That brings us to where we are now.

Thanks again for your time and help :)

**Comment by cubinator** [comment]
The problem is that this library uses many Linux specific functions in order to write to the image, so in order to port this to Windows one needs to find equivalent Win32 APIs, but there is just too much of them for me to handle. Sorry for that ;(

**Comment by superr** [comment]
I understand. Thank you for trying :)

Is the original feature/project request for a Python module also dead? Again, no pressure :)

**Comment by cubinator** [comment]
Yes, I think you can consider it dead... It's just way too much for me.

**Comment by superr** [comment]
Ok, thanks anyway :)

I really appreciate all you have done. Please open this issue again if you ever change your mind :)
