### ISSUE TITLE
Incorrect ext4 files capability

### ISSUE THREAD

**Issue by breakersvd** [cubinator/ext4#8]
Hi @cubinator 
First thanks for all your hard work

Here is a link that explains my problem [ext4.7z](http://www.mediafire.com/file/acp2mrhry14b5nd/ext4.7z/file)

This file contents your ext4 lib and `ext4_analyzer.py` script that I wrote to extract all ext4 file permissions (modes, capability....).
And there are two vendor files `vendor_ok` & `vendor_error`
In the both files the `uid` & `gid` & `modes` are ok but `capability` is not correct in `vendor_error` only.
(The `vendor_ok` is another file that the script works correctly on it)

You could check it easily by running `ext4_analyzer.py vendor_error`
and look for the two lines that have incorrect capabilities:

>-rwxr-xr-x 1010 1010 /bin/hostapd u:object_r:hostapd_exec:s0 capabilities=0x2bc0e80634620200
>-rwxr-xr-x 1010 1010 /bin/hw/android.hardware.wifi@1.0-service u:object_r:hal_wifi_default_exec:s0 capabilities=0x4ac2efa34620200

But the correct is:
 
>-rwxr-xr-x  1010  1010 /bin/hostapd  u:object_r:hostapd_exec:s0  capabilities=0x3000
>-rwxr-xr-x  1010  1010 /bin/hw/android.hardware.wifi@1.0-service  u:object_r:hal_wifi_default_exec:s0  capabilities=0x13000

In the script `ext4_analyzer.py` you can see the capabilities extracting codes (maybe the problem from them i could not fix it)

I tried to mount the `vendor_error` partition in linux and i use `os.getxattr(dir, "security.capability")`
And it gives the correct results.

That is it and thanks in advance.
I'm ready for any suggestion or fixes to test.

Regards.

**Comment by cubinator** [comment]
Looks like some offsets are being calculated incorrectly. Those wrong capabilities are the exact values a few bytes away from the real capabilities. What does the following snippet output for you?

    import ext4
    file = open("vendor_error", "rb")
    volume = ext4.Volume(file)
    hostapd = volume.root.get_inode("bin", "hostapd")
    capability = next((value for name, value in hostapd.xattrs() if name.lower() == "security.capability"), None)
    print(capability)

**Comment by breakersvd** [comment]
@cubinator 
Thanks for reply

There is no any problem with your `ext4` lib, I found the problem:

The `vendor_error` file has 3 xattr (security.selinux & security.five & security.capability)
The problem is with my `ext4_analyzer.py` script in this code `capability = f"{xattrs_perms[1:2]}"`
because I don't search for `security.five` xattr. So this new edit for the script will fix it:

> #!/usr/bin/env python3
> 
> import ext4
> import argparse
> import os
> import sys
> 
> parser = argparse.ArgumentParser(description='Read <modes, symlinks, contexts and capabilities> from an ext4 image')
> parser.add_argument('ext4_image', help='Path to ext4 image to process')
> args = parser.parse_args()
> exists = os.path.isfile(args.ext4_image)
> if not exists:
>     print("Error: input file " f"[{args.ext4_image}]" " was not found")
>     sys.exit(1)
>     
> file = open(args.ext4_image, "rb")
> volume = ext4.Volume(file)
> 
> def scan_dir (root_inode, root_path = ""):
>     for entry_name, entry_inode_idx, entry_type in root_inode.open_dir():
>         if entry_name == "." or entry_name == "..":
>             continue
>         entry_inode = root_inode.volume.get_inode(entry_inode_idx, entry_type)
>         entry_inode_path = root_path + "/" + entry_name
>         if entry_inode.is_dir:
>             scan_dir(entry_inode, entry_inode_path)
>         if entry_inode_path[-1] == '/':
>             continue
>         xattrs_perms = list(entry_inode.xattrs())
>         found_cap = False
>         found_con = False
>         if "security.capability" in f"{xattrs_perms}": found_cap = True
>         if "security.selinux" in f"{xattrs_perms}": found_con = True
>         contexts = ""
>         capability = ""
>         if found_cap:
>             if found_con:
>                 if "security.five" in f"{xattrs_perms}":
>                     capability = f"{xattrs_perms[2:3]}"
>                 else:
>                     capability = f"{xattrs_perms[1:2]}"
>             else:
>                 capability = f"{xattrs_perms[0:1]}"
>             capability = capability.split(" ")[1][:-3][+2:].encode('utf-8').decode('unicode-escape').encode('ISO-8859-1')
>             capability = str(hex(int.from_bytes(capability[4:8] + capability[14:18], "little")))
>             capability = "capabilities="f"{capability}"
>             capability = " "f"{capability}"
>         if found_con:
>             contexts = f"{xattrs_perms[0:1]}"
>             contexts = f"{contexts.split( )[1].split('x00')[0][:-1][+2:]}"
>             contexts = " "f"{contexts}"
>         print(f"{entry_inode.mode_str:s}" " " f"{entry_inode_path}"f"{contexts}"f"{capability}")
> 
> scan_dir(volume.root)
> file.close()

exactly here:

> if "security.five" in f"{xattrs_perms}":
>                     capability = f"{xattrs_perms[2:3]}"
>                 else:
>                     capability = f"{xattrs_perms[1:2]}"

Thanks for your help
