### ISSUE TITLE
Hash trees

### ISSUE THREAD

**Issue by superr** [cubinator/ext4#9]
Hello,

I came across the following error when working with this [ext4 system.img](https://mega.nz/#!KGZgFaSB!LjZ8dQj7XgPlfpvPfrt331kPGoWzYc95YCPhdSF5ZEg):

`NotImplementedError: Hash trees are not implemented yet.`

Do you have plans to implement hash trees?

Thanks :)

EDIT: This system.img mounts in Linux with no issues.

**Comment by cubinator** [comment]
At the moment I have no plans to implement hash trees, because of university (exams + bachelor thesis). Sorry for that :(

**Comment by superr** [comment]
Ok, thank you for your answer. Good luck with exams :)
